# Generated by Django 5.0 on 2024-02-01 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp_Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='myapp_Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='myapp_Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myapp_articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myapp_users')),
            ],
        ),
        migrations.CreateModel(
            name='myapp_Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_favorite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myapp_articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myapp_users')),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
