# Generated by Django 5.0 on 2024-02-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapp_users',
            old_name='userid',
            new_name='user_id',
        ),
    ]
