# Generated by Django 5.0 on 2024-02-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_image_url_myapp_articles_imgurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp_Articles',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='myapp_Comments',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='myapp_Favorites',
            new_name='Favorites',
        ),
        migrations.RenameModel(
            old_name='myapp_Users',
            new_name='Users',
        ),
    ]
